module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}"
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#b3c7f1",
        "primary-fixed": "#d7e2ff",
        "surface-variant": "#e0e3e5",
        "error": "#ba1a1a",
        "surface": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "inverse-primary": "#acc7ff",
        "surface-tint": "#115cb9",
        "secondary-container": "#bfd2fd",
        "primary-container": "#0056b3",
        "primary": "#003f87",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e0e3e5",
        "surface-dim": "#d8dadc",
        "secondary": "#4c5e84",
        "outline": "#727784",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#79f6ed",
        "on-surface": "#191c1e",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#acc7ff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#59dad1",
        "on-surface-variant": "#424752",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1e",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#004491",
        "on-tertiary-fixed-variant": "#00504c",
        "surface-bright": "#f7f9fb",
        "tertiary": "#004a46",
        "background": "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed": "#001a40",
        "surface-container": "#eceef0",
        "on-tertiary-fixed": "#00201e",
        "on-secondary-container": "#475a7f",
        "secondary-fixed": "#d7e2ff",
        "outline-variant": "#c2c6d4",
        "tertiary-container": "#00645f",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-container": "#64e3db",
        "on-secondary-fixed": "#041b3c",
        "on-secondary-fixed-variant": "#34476a",
        "on-primary-container": "#bbd0ff",
        "inverse-surface": "#2d3133"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
